import { StyleSheet, Dimensions } from "react-native";
import Colors from "./Colors";
import FontSize from "./FontSize";

const windowHeight = Dimensions.get("window").height;
const windowWidth = Dimensions.get("window").width;
const tabHeight = 50;
const galleryGridWidth = Math.floor((windowWidth - 20) / 4);
const galleryGridHeight = Math.floor((windowWidth - 20) / 4);

const styles = StyleSheet.create({
  mainContainer: {
    width: windowWidth,
    height: windowHeight,
    backgroundColor: "white",
    flex: 1,
    // alignItems: "center",
  },
  headerTitle: {
    fontSize: FontSize.Antz_Major_Title_btn.fontSize,
    fontWeight:FontSize.Antz_Major_Title_btn.fontWeight,
    color: "grey",
  },
  formContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "white",
  },
  formViews: {
    width: "100%",
    // height: "80%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "white",
  },

  inputFlieds: {
    // borderBottomWidth: 1,
    // borderColor: "grey",
    fontSize: FontSize.Antz_Subtext_Regular.fontSize,
    color: "black",
    borderColor: "#00008B",
  },
  feetBox: {
    padding: "1%",
    left: "55%",
    bottom: "10.5%",
    width: "45%",
  },
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Colors.white,
  },
  body: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 10,
    // paddingHorizontal: 20,
    // paddingVertical: 20,
    paddingVertical: 5,
    backgroundColor: "white",
  },

  TextInputContainer: {
    marginVertical: 20,
  },
  nextBtn: {
    marginVertical: 12,
    backgroundColor: "#7CC0CF",
    width: "40%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 10,
  },
  btnText: {
    color: "white",
  },
  flatListBox: {
    marginTop: 15,
    flex: 1,
    height: "100%",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: "white",
    overflow: "hidden",
  },
  imageBox: {
    padding: 10,
    flex: 1,
    flexDirection: "column",
  },
  imageName: {
    backgroundColor: "rgba(255,255,255, 0.6)",
    position: "absolute",
    bottom: 10,
    left: 10,
    padding: 8,
    borderRadius: 10,
    margin: 10, // width : '100%',
    color: "black",
    // bottom: "150%",
    fontSize: FontSize.Antz_Minor_Medium_title.fontSize,
    fontWeight: FontSize.Antz_Minor_Medium_title.fontWeight,
  },
  blankBoxName: {
    color: "grey",
    bottom: "260%",
    left: "19%",
    fontSize: FontSize.Antz_Minor_Medium_title.fontSize,
    fontWeight: FontSize.Antz_Minor_Medium_title.fontWeight,
  },
  formControlLabel: {
    // top: "3%",
    marginTop: 20,
    // fontSize: 15,
    // fontWeight: '200'
  },
  fieldBox: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderBottomWidth: 0.5,
    borderColor: "grey",
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  labelName: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: Colors.lableSize,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  flex1: { flex: 1 },
  width100: { width: "100%" },
  width85: { width: "85%" },
  width20: { width: "20%" },
  width75: { width: "75%" },
  w100: { width: 100 },
  mt60: { marginTop: 60 },
  mb50: { marginBottom: 50 },
  mb10: { marginBottom: 10 },
  mb0: { marginBottom: 0 },
  ml10: { marginLeft: 10 },
  mr10: { marginRight: 10 },
  mt10: { marginTop: 10 },
  mt5: { marginTop: 5 },
  h50: { height: 50 },
  mh4: { marginHorizontal: 4 },
  p0: { padding: 0 },
  p3: { padding: 3 },
  p5: { padding: 5 },
  p10: { padding: 10 },
  pr5: { paddingRight: 5 },
  pl5: { paddingLeft: 5 },
  pv5: { paddingVertical: 5 },
  h10: { height: 10 },
  heightAuto: { height: "auto" },
  safeAreaViewStyle: { flex: 1, backgroundColor: "transparent" },
  sectionHeaderText: { fontSize: FontSize.Antz_Minor_Title.fontSize, color: Colors.white },
  sectionHeaderTextUser: { fontSize: FontSize.Antz_Minor_Title.fontSize, color: Colors.primary },
  BGWhite: { backgroundColor: Colors.white },
  alignItemsCenter: { alignItems: "center" },
  flexDirectionRow: { display: "flex", flexDirection: "row" },
  justifyContentBetween: { justifyContent: "space-between" },
  justifyContentCenter: { justifyContent: "center" },
  justifyContentAround: { justifyContent: "space-around" },
  textAlignCenter: { textAlign: "center" },
  fontWeightNormal: { fontWeight: "normal" },
  qrDownloadImage: { height: 200, width: 200 },
  downloadFileButtonText: { fontSize: FontSize.Antz_Minor_Title.fontSize, marginHorizontal: 5 },
  listEmptyComponentStyle: {
    color: Colors.textColor,
    textAlign: "center",
    marginTop: 10,
  },
  animalCodeTextInput: { width: "100%", textAlign: "left", fontSize: FontSize.Antz_Body_Regular.fontSize },
  imageContainer: {
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 3,
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  inputContainer: {
    padding: "1%",
  },
  headerTitle: {
    fontSize: FontSize.Antz_Medium_Medium.fontSize,
    fontWeight: FontSize.Antz_Body_Title.fontWeight,
    color: "grey",
  },
  formContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "white",
  },
  formViews: {
    width: "100%",
    // height: "80%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "white",
  },
  inputFlieds: {
    // borderBottomWidth: 1,
    // borderColor: "grey",
    fontSize: FontSize.Antz_Subtext_Regular.fontSize,
    color: "black",
    borderColor: "#00008B",
  },
  feetBox: {
    padding: "1%",
    left: "55%",
    bottom: "10.5%",
    width: "45%",
  },
  container: {
    flex: 1,
    alignItems: "center",
    marginTop: 15,
  },
  body: {
    // flex: 1,
    width: "100%",
    height: "100%",
    paddingHorizontal: 10,
    paddingVertical: 20,
    backgroundColor: "white",
  },

  TextInputContainer: {
    marginVertical: 20,
  },
  nextBtn: {
    marginVertical: 12,
    backgroundColor: "#7CC0CF",
    width: "40%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 10,
  },
  btnText: {
    color: "white",
  },
  mainContainer: {
    width: windowWidth,
    height: windowHeight,
    backgroundColor: "white",
    flex: 1,
    // alignItems: "center",
  },
  mainContainer: {
    backgroundColor: "white",
    flex: 1,
    // alignItems: "center",
  },
  headerTitle: {
    fontSize: FontSize.Antz_Medium_Medium.fontSize,
    fontWeight: FontSize.Antz_Body_Title.fontWeight,
    color: "grey",
  },
  formContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "white",
  },
  formViews: {
    width: "100%",
    // height: "80%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "white",
  },

  inputFlieds: {
    // borderBottomWidth: 1,
    // borderColor: "grey",
    fontSize: FontSize.Antz_Subtext_Regular.fontSize,
    color: "black",
    borderColor: "#00008B",
  },
  feetBox: {
    padding: "1%",
    left: "55%",
    bottom: "10.5%",
    width: "45%",
  },
  container: {
    flex: 1,
    alignItems: "center",
    marginTop: 15,
  },
  body: {
    width: "100%",
    height: "100%",
    marginTop: 500,
    paddingHorizontal: 10,
    // paddingHorizontal: 20,
    // paddingVertical: 20,
    paddingVertical: 5,
    backgroundColor: "white",
  },

  TextInputContainer: {
    marginVertical: 20,
  },
  nextBtn: {
    marginVertical: 12,
    backgroundColor: "#7CC0CF",
    width: "40%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 10,
  },
  btnText: {
    color: "white",
  },
  formControlLabel: {
    // top: "3%",
    marginTop: 20,
    // fontSize: 15,
    // fontWeight: '200'
  },
  fieldBox: {
    alignItems: "center",
    width: "100%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    borderBottomWidth: 0.5,
    borderColor: "grey",
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  labelName: {
    color: Colors.labelColor,
    // lineHeight: 40,
    fontSize: Colors.lableSize,
    paddingLeft: 4,
    height: "auto",
    paddingVertical: 10,
  },
  flex1: { flex: 1 },
  width100: { width: "100%" },
  width85: { width: "85%" },
  width20: { width: "20%" },
  width75: { width: "75%" },
  w100: { width: 100 },
  mt60: { marginTop: 60 },
  mb50: { marginBottom: 50 },
  mb10: { marginBottom: 10 },
  mb0: { marginBottom: 0 },
  ml10: { marginLeft: 10 },
  mr10: { marginRight: 10 },
  mt10: { marginTop: 10 },
  mt5: { marginTop: 5 },
  h50: { height: 50 },
  mh4: { marginHorizontal: 4 },
  p0: { padding: 0 },
  p3: { padding: 3 },
  p5: { padding: 5 },
  p10: { padding: 10 },
  pr5: { paddingRight: 5 },
  pl5: { paddingLeft: 5 },
  pv5: { paddingVertical: 5 },
  h10: { height: 10 },
  heightAuto: { height: "auto" },
  safeAreaViewStyle: { flex: 1, backgroundColor: "transparent" },
  sectionHeaderText: { fontSize: FontSize.Antz_Minor_Regular.fontSize, color: Colors.white },
  sectionHeaderTextUser: { fontSize: FontSize.Antz_Minor_Regular.fontSize, color: Colors.primary },
  BGWhite: { backgroundColor: Colors.white },
  alignItemsCenter: { alignItems: "center" },
  flexDirectionRow: { display: "flex", flexDirection: "row" },
  justifyContentBetween: { justifyContent: "space-between" },
  justifyContentCenter: { justifyContent: "center" },
  justifyContentAround: { justifyContent: "space-around" },
  textAlignCenter: { textAlign: "center" },
  fontWeightNormal: { fontWeight: "normal" },
  qrDownloadImage: { height: 200, width: 200 },
  downloadFileButtonText: { fontSize: FontSize.Antz_Minor_Regular.fontSize, marginHorizontal: 5 },
  listEmptyComponentStyle: {
    color: Colors.textColor,
    textAlign: "center",
    marginTop: 10,
  },
  animalCodeTextInput: { width: "100%", textAlign: "left", fontSize:FontSize.Antz_Body_Regular.fontSize },
  imageContainer: {
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 3,
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  inputContainer: {
    padding: "1%",
  },
  headerTitle: {
    fontSize: FontSize.Antz_Medium_Medium.fontSize,
    fontWeight: FontSize.Antz_Body_Title.fontWeight,
    color: "grey",
  },
  formContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "white",
  },
  formViews: {
    width: "100%",
    // height: "80%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "white",
  },

  inputFlieds: {
    // borderBottomWidth: 1,
    // borderColor: "grey",
    fontSize: FontSize.Antz_Subtext_Regular.fontSize,
    color: "black",
    borderColor: "#00008B",
  },
  feetBox: {
    padding: "1%",
    left: "55%",
    bottom: "10.5%",
    width: "45%",
  },
  container: {
    flex: 1,
    alignItems: "center",
    marginTop: 15,
  },
  body: {
    // flex: 1,
    width: "100%",
    height: "100%",
    paddingHorizontal: 10,
    paddingVertical: 20,
    backgroundColor: "white",
  },

  TextInputContainer: {
    marginVertical: 20,
  },
  nextBtn: {
    marginVertical: 12,
    backgroundColor: "#7CC0CF",
    width: "40%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 10,
  },
  btnText: {
    color: "white",
  },
  radioCircle: {
    height: 20,
    width: 20,
    borderRadius: 20 / 2,
    borderWidth: 2,
    borderColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  radioCircleSelected: {
    height: 20,
    width: 20,
    borderRadius: 20 / 2,
    borderWidth: 2,
    borderColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  selectedRb: {
    width: 10,
    height: 10,
    borderRadius: 10 / 2,
    backgroundColor: Colors.primary,
  },
  inputText: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: Colors.textSize,
    width: "100%",
    color: Colors.textColor,
    textAlign: "left",
    padding: 5,
    borderBottomWidth: 1,
    borderColor: "#ddd",
  },
  inputTextArea: {
    backgroundColor: "#fff",
    height: "auto",
    flexWrap: "wrap",
    fontSize: Colors.textSize,
    width: "50%",
    color: Colors.textColor,
    textAlign: "left",
    padding: 5,
  },
  inputContainer: {
    alignItems: "center",
    width: "90%",
    overflow: "hidden",
    flexDirection: "row",
    padding: 5,
    borderRadius: 3,
    backgroundColor: "#fff",
    height: "auto",
    justifyContent: "space-between",
  },
  form: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 0,
    paddingHorizontal: Colors.formPaddingHorizontal,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: Colors.formBorderRedius,
  },
  rowContainer: {
    borderColor: "#d2d1cd",
    borderRadius: 10,
    paddingVertical: 2,
    borderRadius: 3,
    // paddingHorizontal: 5,
  },

  row: {
    marginTop: 0,
    flexDirection: "row",
    marginBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: "#cfcfcf",
    borderRadius: 3,
    // height: 45,
    width: "100%",
    alignItems: "center",
  },
  rowLeft: {
    width: "50%",
    backgroundColor: "#fff",
    paddingLeft: 10,
    justifyContent: "center",
    marginTop: 0,
    borderRadius: 3,
    // paddingTop:1,
    // paddingBottom:1,
  },
  rowRight: {
    width: "45%",
    marginLeft: 5,
    backgroundColor: "#fff",
    marginVertical: 5,
    textAlign: "left",
    borderRadius: 3,
    justifyContent: "center",
    // paddingBottom: 6
  },
  rowLeftDateFeild: {
    width: "40%",
    backgroundColor: "#fff",
    paddingLeft: 4,
    justifyContent: "center",
    marginTop: 0,
    borderRadius: 3,
  },
  rowRightDateFeild: {
    width: "70%",
    marginLeft: 5,
    backgroundColor: "#fff",
    marginVertical: 5,
    textAlign: "left",
    borderRadius: 3,
    justifyContent: "center",
  },
  textSub: {
    margin: 10,
    color: Colors.textColor,
    fontWeight: "bold",
  },
  tabContainer: {
    width: "100%",
    height: tabHeight,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d1d1",
    borderTopWidth: 1,
    borderTopColor: Colors.primary,
    elevation: 1,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    height: tabHeight,
  },
  activeTab: {
    height: tabHeight - 1,
    borderBottomWidth: 2,
    borderBottomColor: Colors.primary,
  },

  activeTexttab: {
    // style for active tab text
    fontSize: FontSize.Antz_Body_Regular.fontSize,
    fontWeight:FontSize.Antz_Body_Title.fontWeight,
    color: Colors.primary,
  },
  inActiveText: {
    fontSize: FontSize.Antz_Body_Regular.fontSize,
    color: Colors.textColor,
    opacity: 0.8,
  },
  inActiveTab: {
    backgroundColor: Colors.white,
    paddingVertical: 3,
  },
  centerItmW50: {
    flexDirection: "row",
    alignItems: "center",
    width: "50%",
  },
  textfield: {
    height: "auto",
    fontSize: Colors.textSize,
    color: Colors.textColor,
    textAlign: "left",
    padding: 5,
  },
  textfieldTime: {
    justifyContent: "center",
    height: 30,
    fontSize: Colors.textSize,
    color: Colors.textColor,
    textAlign: "center",
  },
  dateField: {
    backgroundColor: "#fff",
    height: "auto",

    fontSize: Colors.textSize,
    color: Colors.textColor,
    textAlign: "left",
    padding: 5,
  },
  modalBtnCover: {
    width: "95%",
    height: 40,
    margin: 10,
    paddingVertical: 2,
    paddingHorizontal: 20,
    marginTop: 10,
    borderRadius: 3,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomPreviewBtnCover: {
    width: "auto",
    height: 40,
    margin: 10,
    paddingVertical: 2,
    paddingHorizontal: 20,
    marginTop: 10,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  bbw0: {
    borderBottomWidth: 0,
  },
  bottomBtnTxt: {
    fontSize: FontSize.Antz_Minor_Regular.fontSize,
    color: Colors.white,
  },
});
export default styles;
